### ISSUE TITLE
Question : how do I run the tests locally ?

### ISSUE THREAD

**Issue by olafleur** [cdroulers/block-fly#21]
For the moment, when I run `npm test` I have this error : 
```
> block-fly@0.10.0 test C:\dev\block-fly
> cross-env NODE_ENV=test mocha --require build/test/testHelpers.js "build/test/**/*spec.js"

module.js:472
    throw err;
    ^

Error: Cannot find module 'build/test/testHelpers.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\dev\block-fly\node_modules\mocha\bin\_mocha:345:3
    at Array.forEach (native)
    at Object.<anonymous> (C:\dev\block-fly\node_modules\mocha\bin\_mocha:344:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
npm ERR! Test failed.  See above for more details.
```

When I look in my `build` directory, there is no `test` subdirectory.
How do I create it and how do I get the `testHelpers.js` file ?

**Comment by cdroulers** [comment]
Npm run build before to compile the typescript to js. Ts-node didn't work
properly for some reason.

**Comment by olafleur** [comment]
Thanks !
